version: "3.8"

services:
  ollama:
    image: docker.io/ollama/ollama
    container_name: ollama
    networks:
      - llm-net
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    networks:
      - llm-net
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3500:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

networks:
  llm-net:
    external: true

volumes:
  ollama-data:
    external: true
  open-webui:
    external: true